name: Trigger dbt Cloud Job

on:
  push:
    branches:
      - main

jobs:
  dbt_cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger dbt Cloud job
        env:
          DBT_API_KEY: ${{ secrets.DBT_KEY }}
        run: |
          curl -v -H "Authorization: Bearer $DBT_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"cause": "Triggered by GitHub Actions", "git_branch": "main"}' \
            https://cloud.getdbt.com/api/v2/accounts/172022/jobs/252630/run/
